# Generated by Django 3.1.5 on 2021-02-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210208_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
