# Generated by Django 3.1.5 on 2021-02-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='currentBid',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='nextBid',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
