# Generated by Django 3.1.5 on 2021-02-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210212_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item',
            new_name='item_id',
        ),
    ]
