# Generated by Django 3.1.5 on 2021-02-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210212_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item_id',
            new_name='item',
        ),
    ]
