# Generated by Django 3.1.5 on 2021-02-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('NotDefined', 'Not defined'), ('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Car', 'Car'), ('Travel', 'Travel'), ('Fun', 'Fun')], max_length=25),
        ),
    ]
