# Generated by Django 3.1.5 on 2021-02-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210209_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comments',
        ),
    ]
