# Generated by Django 3.1.5 on 2021-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='bidWinner',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
