# Generated by Django 3.1.5 on 2021-02-20 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_bidwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
